<?php

/** @var \ClassyLlama\AvaTax\Block\Adminhtml\Log\View $block */
$logModel = $block->getLog();
?>
<div class="entry-edit form-inline">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php echo __('Log Data'); ?></span>
        </legend><br />

        <div id="log_details_fieldset" class="field log-details">
            <table class="admin__table-secondary">
                <colgroup>
                    <col width="25%" />
                    <col />
                </colgroup>
                <tbody>
                <tr>
                    <th><?php echo __('Log ID'); ?></th>
                    <td><?php echo $logModel->getId(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Log Time'); ?></th>
                    <td><?php echo $logModel->getCreatedAt(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Store ID'); ?></th>
                    <td><?php echo $logModel->getStoreId(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Level'); ?></th>
                    <td><?php echo $logModel->getLevel(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Message'); ?></th>
                    <td><?php echo $logModel->getMessage(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Source'); ?></th>
                    <td><?php echo $logModel->getSource(); ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </fieldset>

    <?php if ($logModel->getRequest()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Request');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <?php echo $block->escapeHtml($logModel->getRequest()) ?>
            </div>
        </fieldset>
        <?php
    } ?>

    <?php if ($logModel->getResult()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Result');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <?php echo $block->escapeHtml($logModel->getResult()) ?>
            </div>
        </fieldset>
        <?php
    } ?>

    <?php if ($logModel->getAdditional()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Additional');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <?php echo $block->escapeHtml($logModel->getAdditional()) ?>
            </div>
        </fieldset>
        <?php
    } ?>
</div>
