<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \ClassyLlama\AvaTax\Block\Adminhtml\Log\View $block */
$logModel = $block->getLog();
?>
<div class="entry-edit form-inline">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php echo __('Log Data'); ?></span>
        </legend><br />

        <div id="log_details_fieldset" class="field log-details">
            <table class="admin__table-secondary">
                <colgroup>
                    <col width="25%" />
                    <col />
                </colgroup>
                <tbody>
                <tr>
                    <th><?php echo __('Log ID'); ?></th>
                    <td><?php echo $logModel->getId(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Log Time'); ?></th>
                    <td><?php echo $logModel->getCreatedAt(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Store ID'); ?></th>
                    <td><?php echo $logModel->getStoreId(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Level'); ?></th>
                    <td><?php echo $logModel->getLevel(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Message'); ?></th>
                    <td><?php echo $logModel->getMessage(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Source'); ?></th>
                    <td><?php echo $logModel->getSource(); ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </fieldset>

    <?php if ($logModel->getRequest()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Request');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <pre class="admin__avatax-log-text"><?php echo $block->escapeHtml($logModel->getRequest()) ?></pre>
            </div>
        </fieldset>
        <?php
    } ?>

    <?php if ($logModel->getResult()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Result');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <pre class="admin__avatax-log-text"><?php echo $block->escapeHtml($logModel->getResult()) ?></pre>
            </div>
        </fieldset>
        <?php
    } ?>

    <?php if ($logModel->getAdditional()) {
        ?>
        <fieldset class="fieldset">
            <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Additional');
                ?></span>
            </legend><br />

            <div class="field log-details-grid">
                <pre class="admin__avatax-log-text"><?php echo $block->escapeHtml($logModel->getAdditional()) ?></pre>
            </div>
        </fieldset>
        <?php
    } ?>
</div>
