<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": <?= $this->isValidationEnabled() ?>,
                "hasChoice": <?= $this->getChoice() ?>,
                "instructions": <?= $this->getInstructions() ?>,
                "errorInstructions": <?= $this->getErrorInstructions() ?>,
                "countriesEnabled": "<?= $this->getCountriesEnabled() ?>"
            }
        }
    }
</script>
<script type="text/javascript">
    window.avaTaxStoreCode = "<?= $this->getStoreCode() ?>";
</script>
