<script type="text/x-magento-init">
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": <?= $this->isValidationEnabled() ?>,
                "hasChoice": <?= $this->getChoice() ?>,
                "instructions": "<?= $this->getInstructions() ?>",
                "errorInstructions": "<?= $this->getErrorInstructions() ?>",
                "countriesEnabled": "<?= $this->getCountriesEnabled() ?>"
            }
        }
    }
</script>
<script type="text/javascript">
    window.avaTaxStoreCode = "<?= $this->getStoreCode() ?>";
</script>
