<?php

use ClassyLlama\AvaTax\Block\Multishipping\Checkout\Billing;

/**
 * Multishipping checkout billing information
 *
 * @var $block Billing
 */

?>
<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"billingLoader": {}}'>
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')); ?>"
             style="position: absolute;">
    </div>
</div>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getCheckoutData()->getSerializedCheckoutConfigs(); ?>;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
</script>
<div data-mage-init='{"multiShippingAddressValidation":{}}'></div>
<div id="checkout" data-bind="scope:'checkoutMessages'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "checkoutMessages": {
                            "component": "Magento_Ui/js/view/messages",
                            "displayArea": "messages"
                        }
                    }
                }
            }
        }
    </script>
</div>
<form action="<?= $block->escapeUrl($block->getPostActionUrl()); ?>"
      method="post"
      id="multishipping-billing-form"
      class="form multicheckout billing address-validation-multicheckout">
    <div class="block block-billing">
        <div class="block-content">
            <?php if ($block->isValidationEnabled() && $validationResult = $block->validateAddress($block->getAddress())): ?>
                <?php if ($validationResult["error"]): ?>
                    <div class="multishipping-checkout checkout-validate-address">
                        <div class="errorMessageContainer">
                            <?= __("We were unable to validate your address.") ?>
                            <div class="instructions">
                                <p> <?= $validationResult["errorInstructions"] ?></p>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <?php if ($validationResult['isDifferent']): ?>
                        <div class="multishipping-checkout checkout-validate-address">
                            <div class="instructions noError">
                                <?= /* @noEscape */
                                $validationResult['instructions'];
                                ?>
                            </div>
                            <?php if ($validationResult['hasChoice']): ?>
                                <div class="form validate noError">
                                    <div class="validContainer addressOption selected">
                                        <div class="addressRadio">
                                            <input type="radio" class="validAddress av-radiobutton"
                                                   name=<?= /* @noEscape */
                                                   "addressToUse" ?>
                                                   checked
                                                   id="<?= /* @noEscape */
                                                   "valid" ?>"
                                                   data-address='<?= $validationResult['validAddress'] ?>'
                                            />
                                        </div>
                                        <label for="<?= /* @noEscape */
                                        "valid" ?>" class="addressLabel">
                                            <div class="optionTitle"><?= __('Suggested Address'); ?></div>
                                            <div class="optionAddress validAddressText">
                                                <?= /* @noEscape */
                                                $validationResult['validAddressHtml']; ?>
                                            </div>
                                        </label>
                                    </div>
                                    <div class="originalContainer addressOption">
                                        <div class="addressRadio">
                                            <input type="radio" class="originalAddress av-radiobutton"
                                                   name=<?= /* @noEscape */
                                                   "addressToUse" ?>
                                                   id="<?= /* @noEscape */
                                                   'original' ?>"
                                                   data-address='<?= $validationResult['originalAddress'] ?>'
                                            />
                                        </div>
                                        <label for="<?= "original" ?>" class="addressLabel">
                                            <div class="optionTitle">
                                                <?= __('Original Address'); ?>
                                            </div>
                                            <div class="optionAddress originalAddressText">
                                                <?= /* @noEscape */
                                                $validationResult['originalAddressHtml']; ?>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            <div class="box box-billing-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')); ?></span>
                    <a href="<?= $block->escapeUrl($block->getSelectAddressUrl()); ?>" class="action">
                        <span><?= $block->escapeHtml(__('Change')); ?></span>
                    </a>
                </strong>
                <div class="box-content">
                    <address>
                        <?= /* @noEscape */
                        $block->getCheckoutData()->getAddressHtml($block->getAddress()); ?>
                    </address>
                </div>
            </div>
            <div class="box box-billing-method">
                <fieldset class="fieldset">
                    <legend class="legend box-title">
                        <span><?= $block->escapeHtml(__('Payment Method')); ?></span>
                    </legend>
                    <br>
                    <div class="box-content">
                        <?= $block->getChildHtml('payment_methods_before') ?>
                        <?php /* Payment methods forms list */ ?>
                        <dl class="checkout-payment-method" id="payment-methods">
                            <?php
                            $methods = $block->getMethods();
                            $methodsCount = count($methods);
                            $methodsForms = $block->hasFormTemplates() ? $block->getFormTemplates() : [];

                            foreach ($methods as $_method) :
                                $code = $_method->getCode();
                                $checked = $block->getSelectedMethodCode() === $code;

                                if (isset($methodsForms[$code])) {
                                    $block->setMethodFormTemplate($code, $methodsForms[$code]);
                                }
                                ?>
                                <div data-bind="scope: 'payment_method_<?= $block->escapeHtml($code); ?>'">
                                    <dt class="item-title">
                                        <?php if ($methodsCount > 1) : ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   title="<?= $block->escapeHtmlAttr($_method->getTitle()) ?>"
                                                   data-bind="
                                                       value: getCode(),
                                                       checked: isChecked,
                                                       click: selectPaymentMethod,
                                                       visible: isRadioButtonVisible()"
                                                <?php if ($checked) : ?>
                                                    checked="checked"
                                                <?php endif; ?>
                                                   class="radio"/>
                                        <?php else : ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   data-bind="
                                                       value: getCode(),
                                                       afterRender: selectPaymentMethod"
                                                   checked="checked"
                                                   class="radio solo method"/>
                                        <?php endif; ?>
                                        <label for="p_method_<?= $block->escapeHtml($code); ?>">
                                            <?= $block->escapeHtml($_method->getTitle()) ?>
                                        </label>
                                    </dt>
                                    <?php if ($html = $block->getChildHtml('payment.method.' . $code)) : ?>
                                        <dd class="item-content <?= $checked ? '' : 'no-display'; ?>">
                                            <?= /* @noEscape */
                                            $html; ?>
                                        </dd>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </dl>
                        <?= $block->getChildHtml('payment_methods_after') ?>
                        <?= $block->getChildHtml('checkout_billing_items') ?>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary" id="parent-payment-continue">
            <button id="payment-continue"
                    type="button"
                    class="action primary continue">
                <span><?= $block->escapeHtml(__('Go to Review Your Order')); ?></span>
            </button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()); ?>" class="action back">
                <span><?= $block->escapeHtml(__('Back to Shipping Information')); ?></span>
            </a>
        </div>
    </div>
</form>
<script>
    require(['jquery', 'mage/mage'], function (jQuery) {
        var addtocartForm = jQuery('#multishipping-billing-form');

        addtocartForm.mage('payment', {
            checkoutPrice: <?= (float)$block->getQuoteBaseGrandTotal() ?>
        });

        addtocartForm.mage('validation', {
            errorPlacement: function (error, element) {
                if (element.attr('data-validate') && element.attr('data-validate').indexOf('validate-cc-ukss') >= 0) {
                    element.parents('form').find('[data-validation-msg="validate-cc-ukss"]').html(error);
                } else {
                    element.after(error);
                }
            }
        });
    });
</script>

<script>
    //<![CDATA[
    require(
        [
            'Magento_Checkout/js/model/quote',
            'jquery',
            'domReady!'
        ], function (quote, $) {
            quote.billingAddress({
                city: '<?= /* @noEscape */ $block->getAddress()->getCity() ?>',
                company: '<?= /* @noEscape */ $block->getAddress()->getCompany(); ?>',
                countryId: '<?= /* @noEscape */ $block->getAddress()->getCountryId(); ?>',
                customerAddressId: '<?= /* @noEscape */ $block->getAddress()->getCustomerAddressId(); ?>',
                customerId: '<?= /* @noEscape */ $block->getAddress()->getCustomerId(); ?>',
                fax: '<?= /* @noEscape */ $block->getAddress()->getFax(); ?>',
                firstname: '<?= /* @noEscape */ $block->getAddress()->getFirstname(); ?>',
                lastname: '<?= /* @noEscape */ $block->getAddress()->getLastname(); ?>',
                postcode: '<?= /* @noEscape */ $block->getAddress()->getPostcode(); ?>',
                regionId: '<?= /* @noEscape */ $block->getAddress()->getRegionId(); ?>',
                regionCode: '<?= /* @noEscape */ $block->getAddress()->getRegionCode() ?>',
                region: '<?= /* @noEscape */ $block->getAddress()->getRegion(); ?>',
                street: <?= /* @noEscape */ json_encode($block->getAddress()->getStreet()); ?>,
                telephone: '<?= /* @noEscape */ $block->getAddress()->getTelephone(); ?>'
            });
        });
    //]]>
</script>
<script type="text/javascript">
    window.avaTaxStoreCode = "<?= $this->getStoreCode() ?>";
</script>
