<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

namespace ClassyLlama\AvaTax\Controller\Certificates;

use ClassyLlama\AvaTax\Helper\UrlSigner;
use Magento\Customer\Api\CustomerRepositoryInterface;
use Magento\Framework\DataObjectFactory;
use Magento\Framework\Exception\NotFoundException;

class Download extends \Magento\Framework\App\Action\Action
{
    /**
     * @var \Magento\Framework\Controller\Result\RawFactory
     */
    protected $resultRawFactory;

    /**
     * @var \Magento\Framework\App\Response\Http\FileFactory
     */
    protected $fileFactory;

    /**
     * @var \ClassyLlama\AvaTax\Api\RestCustomerInterface
     */
    protected $customerRest;

    /**
     * @var UrlSigner
     */
    protected $urlSigner;

    /**
     * @var CustomerRepositoryInterface
     */
    protected $customerRepository;

    /**
     * @var DataObjectFactory
     */
    protected $dataObjectFactory;

    /**
     * Download constructor.
     *
     * @param \Magento\Framework\Controller\Result\RawFactory  $resultRawFactory
     * @param \Magento\Framework\App\Response\Http\FileFactory $fileFactory
     * @param \ClassyLlama\AvaTax\Api\RestCustomerInterface    $customerRest
     * @param UrlSigner                                        $urlSigner
     * @param CustomerRepositoryInterface                      $customerRepository
     * @param DataObjectFactory                                $dataObjectFactory
     * @param \Magento\Backend\App\Action\Context              $context
     */
    public function __construct(
        \Magento\Framework\Controller\Result\RawFactory $resultRawFactory,
        \Magento\Framework\App\Response\Http\FileFactory $fileFactory,
        \ClassyLlama\AvaTax\Api\RestCustomerInterface $customerRest,
        UrlSigner $urlSigner,
        CustomerRepositoryInterface $customerRepository,
        DataObjectFactory $dataObjectFactory,
        \Magento\Backend\App\Action\Context $context
    )
    {
        parent::__construct($context);

        $this->resultRawFactory = $resultRawFactory;
        $this->fileFactory = $fileFactory;
        $this->customerRest = $customerRest;
        $this->urlSigner = $urlSigner;
        $this->customerRepository = $customerRepository;
        $this->dataObjectFactory = $dataObjectFactory;
    }

    /**
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface
     * @throws \Exception
     */
    public function execute()
    {
        $customerId = $this->getRequest()->getParam('customer_id');
        $certificateId = $this->getRequest()->getParam('certificate_id');
        $expires = (int)$this->getRequest()->getParam('expires');
        $signature = null;
        $storeId = null;

        $parameters = $this->getRequest()->getParams();

        if (isset($parameters['signature'])) {
            $signature = $parameters['signature'];
            unset($parameters['signature']);
        }

        // Ensure that this was a valid request generated by the system
        if (time() > $expires || $signature !== $this->urlSigner->signParameters($parameters)) {
            throw new NotFoundException(__('No certificate found'));
        }

        // If we have specified a customer ID, use the store that user is associated with, otherwise default to session
        if ($customerId !== null) {
            $customerModel = $this->customerRepository->getById($customerId);
            $storeId = $customerModel->getStoreId();
        }

        $certificateStream = $this->customerRest->downloadCertificate(
            $this->dataObjectFactory->create(['data' => ['id' => $certificateId]]),
            null,
            $storeId
        );

        $resultRaw = $this->resultRawFactory->create();
        $resultRaw->setHeader('Content-type', 'application/pdf', true)->setHeader(
            'Content-Disposition',
            'inline; filename="certificate.pdf"',
            true
        )->setContents($certificateStream); //set content for download file here

        return $resultRaw;
    }
}