<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \ClassyLlama\AvaTax\Block\Adminhtml\Queue\Summary $block */
$lastUpdatedAt = $block->getQueueSummaryLastUpdatedAt();
$count = $block->getQueueSummaryCount();
?>
<div class="admin__avatax-queue-summary">
    <?php echo __('Last Processed at %1 - Queue Records Waiting To Be Processed: %2', $lastUpdatedAt, $count); ?>
</div>
