<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \ClassyLlama\AvaTax\Block\Adminhtml\Queue\Summary $block */
$lastUpdatedAt = $block->getQueueSummaryLastUpdatedAt();
$count = $block->getQueueSummaryCount();
$count = htmlspecialchars($count, ENT_QUOTES, 'UTF-8');
?>
<div class="admin__avatax-queue-summary">
    <?php echo __('Last Processed at %1 - Queue Records Waiting To Be Processed: %2', $lastUpdatedAt, $count); ?><br>
    <em><?php echo __('Note: Queued items will not be processed until %1 minutes after they are created <a href="%2">to avoid race conditions during order processing</a>.', (\ClassyLlama\AvaTax\Model\Queue\Processing\ProcessingStrategyInterface::QUEUE_PROCESSING_DELAY / 60), 'https://github.com/classyllama/ClassyLlama_AvaTax/issues/170') ?></em>
</div>
