<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \ClassyLlama\AvaTax\Block\Adminhtml\Queue\Summary $block */
$lastUpdatedAt = $block->getQueueSummaryLastUpdatedAt();
$count = $block->getQueueSummaryCount();
?>
<div class="admin__avatax-queue-summary">
    <?php echo __('Last Processed at %1 - Queue Records Waiting To Be Processed: %2', $lastUpdatedAt, $count); ?><br>
    <em><?php echo __('Note: Queued items will not be processed until 2 minutes after they are created <a href="%1">to avoid race conditions during order placement</a>.', 'https://github.com/classyllama/ClassyLlama_AvaTax/issues/170') ?></em>
</div>
