<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

?>
<?php $url = $this->getUrl(
    'avatax/companycodes/get',
    ['form_key' => $this->getFormKey(), 'mode' => $this->getData('avatax_mode')]
); ?>
<input id="<?php echo $this->getData('company_code_id') ?>"
       name="groups[<?php echo $this->getData('company_code_group') ?>][fields][<?php echo $this->getData(
           'company_code_field'
       ) ?>][value]" value="" type="hidden">
<script type="text/x-magento-init">
{
    "#<?php echo $this->getData('company_id_id') ?>": {
        "ClassyLlama_AvaTax/js/form/field/company-code": {
            "url": "<?php echo $url ?>",
            "accountNumberId": "<?php echo $this->getData('account_number_id') ?>",
            "licenseKeyId": "<?php echo $this->getData('license_key_id') ?>",
            "companyCodeId": "<?php echo $this->getData('company_code_id') ?>"
        }
    }
}

</script>
