<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
/** @var \ClassyLlama\AvaTax\Block\ViewModel\CustomerCertificates $viewModel */
$viewModel = $this->getViewModel();
?>
<?php if ($viewModel->shouldShowWarning()): ?>
    <p class="message">
        <?= __('Please note that you can only view certificates for a customer from the website/store that customer
        is associated to. This means if you have 2 different Avalara credentials for 2 different stores and one customer
        uploads certificates to both, only certificates uploaded through the store that customer is associated to will
        be visible here.') ?>
    </p>
<?php endif ?>
<div id="<?= $block->escapeHtml($block->getId()) ?>" data-grid-id="<?= $block->escapeHtml($block->getId()) ?>">
    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <table class="data-grid" id="<?= $block->escapeHtml($block->getId()) ?>_table">
            <thead>
                <tr>
                    <th class="data-grid-th"><?php echo __('State') ?></th>
                    <th class="data-grid-th"><?php echo __('Signed Date') ?></th>
                    <th class="data-grid-th"><?php echo __('Expiration Date') ?></th>
                    <th class="data-grid-th"><?php echo __('Status') ?></th>
                    <th class="data-grid-th" colspan="3">&nbsp;</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($viewModel->getCertificates() as $certificate): ?>
                    <tr data-role="row">
                        <td><?php echo $certificate->getData('exposure_zone')->getData('name'); ?></td>
                        <td><?php echo $certificate->getData('signed_date'); ?></td>
                        <td><?php echo $certificate->getData('expiration_date'); ?></td>
                        <td><?php echo $certificate->getData('valid') ? __('Approved') : __('Denied'); ?></td>
                        <td>
                            <?php if ($certificate->getData('valid')): ?>
                                <a target="_blank"
                                   href="<?php echo $viewModel->getCertificateUrl($certificate->getData('id')) ?>">
                                    <?= __('View Certificate') ?>
                                </a>
                            <?php endif ?>
                        </td>
                        <td>
                            <?php if ($certificate->getData('valid')): ?>
                                <a href="javascript:void(0)"><?= __('Renew Certificate') ?></a>
                            <?php endif ?>
                        </td>
                        <td>
                            <?php if ($certificate->getData('valid')): ?>
                                <a href="javascript:void(0)"><?= __('Delete Certificate') ?></a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>

                <?php if (count($viewModel->getCertificates()) === 0): ?>
                    <tr class="data-grid-tr-no-data even">
                        <td class="empty-text" colspan="7"><?= __('No certificates found for this customer') ?></td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>