<?php
/**
 * @category    ClassyLlama
 * @copyright   Copyright (c) 2018 Classy Llama Studios, LLC
 * @author      sean.templeton
 */
/** @var \ClassyLlama\AvaTax\Block\Adminhtml\CustomerCertificates $block */
?>
<div id="<?= $block->escapeHtml( $block->getId() ) ?>" data-grid-id="<?= $block->escapeHtml( $block->getId() ) ?>">
    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <table class="data-grid" id="<?= $block->escapeHtml( $block->getId() ) ?>_table">
            <thead>
            <tr>
                <th class="data-grid-th"><?php echo __( 'State' ) ?></th>
                <th class="data-grid-th"><?php echo __( 'Signed Date' ) ?></th>
                <th class="data-grid-th"><?php echo __( 'Expiration Date' ) ?></th>
                <th class="data-grid-th"><?php echo __( 'Status' ) ?></th>
                <th class="data-grid-th" colspan="3">&nbsp;</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($block->getCertificates() as $certificate): ?>
                <tr data-role="row">
                    <td><?php echo $certificate->getData( 'exposure_zone' )->getData('name'); ?></td>
                    <td><?php echo $certificate->getData( 'signed_date' ); ?></td>
                    <td><?php echo $certificate->getData( 'expiration_date' ); ?></td>
                    <td><?php echo $certificate->getData( 'valid' ) ? 'Approved' : 'Denied'; ?></td>
                    <td>
                        <?php if ($certificate->getData('valid')): ?>
                            <a target="_blank" href="<?php echo $block->getCertificateUrl($certificate->getData('id')) ?>">View Certificate</a>
                        <?php endif ?>
                    </td>
                    <td>
                        <?php if ($certificate->getData('valid')): ?>
                            <a href="javascript:void(0)">Renew Certificate</a>
                        <?php endif ?>
                    </td>
                    <td>
                        <?php if ($certificate->getData('valid')): ?>
                            <a href="javascript:void(0)">Delete Certificate</a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>

            <?php if(count($block->getCertificates()) === 0): ?>
                <tr class="data-grid-tr-no-data even">
                    <td class="empty-text" colspan="7">No certificates found for this customer</td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>