<?php if ($block->isValidationEnabled()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": <?= $this->isValidationEnabled() ?>,
                "instructions": <?= $this->getInstructions() ?>,
                "errorInstructions": <?= $this->getErrorInstructions() ?>,
                "countriesEnabled": "<?= $this->getCountriesEnabled() ?>",
                "baseUrl": "<?= $this->getBaseUrl() ?>"
            }
        }
    }
</script>
<?php endif; ?>
