<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if ($block->isValidationEnabled()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": <?= (int)$this->isValidationEnabled() ?>,
                "instructions": <?= $this->getInstructions() ?>,
                "errorInstructions": <?= $this->getErrorInstructions() ?>,
                "countriesEnabled": "<?= $this->getCountriesEnabled() ?>",
                "baseUrl": "<?= $this->getBaseUrl() ?>"
            }
        }
    }
</script>
<?php endif; ?>
